### ISSUE TITLE
Highlighted selected lines highlight js plugin

### ISSUE THREAD

**Issue by Yukaii** [Yukaii/daily-oops#2]
https://fluidframework.com/docs/advanced/doc-system/#syntax-formatting-and-line-highlighting

### Hugos syntax

~~~md
```ts {linenos=inline,hl_lines=["2-6",9]}
~~~

### Proposed syntax (Reveal.js like)

~~~md
```ts=123 [135-146,122]
// start from line 123, with ranges [135-146] and 122 highlighted
```

```ts= [3-5]
// no line number offset, with range [3-5] highlighted
```
~~~

### TODOs

- [x] Adjust dark mode gutter text color
- [x] pre/tbody padding right
- [x] toggle line number
- [x] ranges

### References

- https://github.com/wcoder/highlightjs-line-numbers.js
- https://revealjs.com/code/#line-numbers-highlights
  - https://github.com/hakimel/reveal.js/blob/master/plugin/highlight/plugin.js#L304
  - https://github.com/hakimel/reveal.js/blob/master/plugin/markdown/plugin.js#L16
- GitHub's file view
